### ISSUE TITLE
Pre-trained model loading error

### ISSUE THREAD

**Issue by bobo0810** [Tencent/TFace#10]
Thank you very much for this work！

Inconsistent quantities caused the loading to fail. Do you know why? Thanks~
- `tasks/distfc/README.md`  IR101 pretrained model:  OrderedDict len is 672
- `torchkit/backbone/model_irse.py` IR101：OrderedDict len is 917

**Comment by HuangYG123** [comment]
Sorry for the inconsistency. This pre-trained model is trained using the code of the original paper version. You can use load this pre-train model with the model definition file in https://github.com/HuangYG123/CurricularFace/blob/master/backbone/model_irse.py.
We will release new pre-trained models with this version of the code soon.

**Comment by bobo0810** [comment]
> Sorry for the inconsistency. This pre-trained model is trained using the code of the original paper version. You can use load this pre-train model with the model definition file in https://github.com/HuangYG123/CurricularFace/blob/master/backbone/model_irse.py.
> We will release new pre-trained models with this version of the code soon.

Thanks:blush:
