### ISSUE TITLE
为什么四种伪造方法训练结果一样？

### ISSUE THREAD

**Issue by XyStruggling** [Tencent/TFace#128]
为什么对DeepFace，Face2Face，FaceSwap，NeuralTextures四种数据集的训练测试结果一样，我的结果，acc都是0.5893，RealAcc都是0.9714，FakeAcc都是0.2071，Loss都是0.62905，lr都是0.001?求大佬们解答，谢谢啦！！！

**Comment by YuXiaolu801** [comment]
修改ffpp.yaml中的数据集
