### ISSUE TITLE
How to run example?

### ISSUE THREAD

**Issue by huytuong010101** [Tencent/TFace#17]
## Thank you for perfect repository <3
- I see that you implemented many papers in `task` directory. I see training code but I cannot see any example code to run that model
- Can you show me how to run with pre-trained model in `TFace/tasks/cifp/` ? (Extract feature + verify)
- Thank you so much

**Comment by wjxzju** [comment]
If you just want to load the pre-trained model and test, please go to the test folder, run verification_rfw.py
