### ISSUE TITLE
Verification dataset

### ISSUE THREAD

**Issue by dongxuemin666** [Tencent/TFace#27]
could u please tell me how to aquire the verification datasets such as "lfw.bin"

THX

**Comment by dongxuemin666** [comment]
done

**Comment by Lingcan-M** [comment]
> done

do you know  how to aquire the verification datasets such as "lfw.bin"?
I have the same problem now.

**Comment by dongxuemin666** [comment]
You can try this pipeline(https://github.com/umairanis03/facial-recognition/blob/8344e040ea61a14a70a4e12a2c097540c3b5b5de/validation_prep.md) and make it by yourself.
You can also search on the Internet for released bin files

**Comment by Lingcan-M** [comment]
> You can try this pipeline(https://github.com/umairanis03/facial-recognition/blob/8344e040ea61a14a70a4e12a2c097540c3b5b5de/validation_prep.md) and make it by yourself.
> You can also search on the Internet for released bin files
Thank you very much for your quick reply.

I found a very good answer(https://github.com/Lingcan-M/verification-datasets-such-as-lfw.bin), hope it helps others

**Comment by dongxuemin666** [comment]
Nice, wish your work going smoothly

**Comment by CloudWalking0** [comment]
> > You can try this pipeline(https://github.com/umairanis03/facial-recognition/blob/8344e040ea61a14a70a4e12a2c097540c3b5b5de/validation_prep.md) and make it by yourself.
> > You can also search on the Internet for released bin files
> 
> Thank you very much for your quick reply. I found a very good answer(https://github.com/Lingcan-M/verification-datasets-such-as-lfw.bin), hope it helps ot

> > You can try this pipeline(https://github.com/umairanis03/facial-recognition/blob/8344e040ea61a14a70a4e12a2c097540c3b5b5de/validation_prep.md) and make it by yourself.
> > You can also search on the Internet for released bin files
> 
> Thank you very much for your quick reply. I found a very good answer(https://github.com/Lingcan-M/verification-datasets-such-as-lfw.bin), hope it helps others

Hello, I want to evaluation on RFW dataset. But I don't know how to get 'African_test.bin', 'Asian_test.bin', 'Caucasian_test.bin', 'Indian_test.bin'. Do you have them?
Thank you very much and have a nice day~
