### ISSUE TITLE
Can you provide the pretrained models ?

### ISSUE THREAD

**Issue by deep-practice** [Tencent/TFace#3]

**Comment by anoymous-face** [comment]
> _No description provided._

@deep-practice Can you find any link to their paper(e.g. Spherical Confidence Learning.. Consistent instance )? If so, would you please share the link?

**Comment by wjxzju** [comment]
@deep-practice which pretrain model do you want

**Comment by zineos** [comment]
I want to all pretrain model

**Comment by stonejane** [comment]
> @deep-practice which pretrain model do you want

Thanks for ur great work!! 🙇‍♀️Could you kindly provide the pretrained model of DCN?My email is 1286306044@qq.com

**Comment by talalz94** [comment]
kindle share the pretrain model files anti-spoofing models talalz994@gmail.com

**Comment by weathon** [comment]
Could we have the MinusFace Model? @wjxzju  wg25r@student.ubc.ca
