### ISSUE TITLE
Face-antispoof pretrained model

### ISSUE THREAD

**Issue by tyyff** [Tencent/TFace#62]
Recently, I am reproducing your paper--ANRL. I have four datasets(I&C&M&O), and train  a model based on your source code. In I&C&m to O task, the EER of O is above 0.3, while in the training dataset, the EER is very low, below 0.001. I don't know why. Can you provide me a pretrained model.

**Comment by ngoanpv** [comment]
Hi @tyyff, I would like to reproduce anti-spoofing papers for my research. 
But I cannot access to Replay Attack dataset (I). 
Could you please share this database? 
My email: 1870468@hcmut.edu.vn
I really appreciate any help you can provide.
