### ISSUE TITLE
请问训练时 --pts_list=${pts_list}  参数填写什么内容

### ISSUE THREAD

**Issue by liyuhui** [Tencent/TFace#9]

**Comment by wjxzju** [comment]
pts_list指的是landmark文件，每一行是图片路径+10个5点的坐标值，中间以空格分开

**Comment by Lingcan-M** [comment]
> pts_list指的是landmark文件，每一行是图片路径+10个5点的坐标值，中间以空格分开

Where can I get this file？I can not find this file in the official dataset.
